---
- hosts: all

  vars_files:
    - home.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
